# nome do workflow
name: Meu primeiro workflow

# evento, ou seja, quando ele entra em execução
on: 
  push:
    branches:
      - develop

# especificando os jobs deste workflow
jobs:
  
  # nome do primeiro job
  primeiro_job:
    # runner do primeiro job
    runs-on: ubuntu-latest
    steps: 
      # primeiro step
      - name: Hello, Github Actions!
        run: echo "Hello, Github Actions!"
      #segundo step
      - name: Qual o direotrio atual?
        run: pwd
      # terceiro step
      - name: Qual o conteúdo do diretório, incluindo arquivos ocultos?
        run: ls -a
      - name: Até mais!
        run: |
          echo "See you, Github Action!"
          echo "Bye!"
          echo "Bye yet again"
      - name: checkout
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"

      - name: teste
        run: echo "teste"
      




