# nome do workflow
name: Meu primeiro workflow

# evento, ou seja, quando ele entra em execução
on: 
  push:
    branches:
      - develop

# especificando os jobs deste workflow
jobs:
  
  # nome do primeiro job
  primeiro_job:
    # runner do primeiro job
    runs-on: ubuntu-latest
    steps: 
      # primeiro step
      - name: Hello, Github Actions!
        run: echo "Hello, Github Actions!"
      #segundo step
      - name: Qual o direotrio atual?
        run: pwd
      # terceiro step
      - name: Qual o conteúdo do diretório, incluindo arquivos ocultos?
        run: ls -a
      - name: Até mais!
        run: |
          echo "See you, Github Action!"
          echo "Bye!"
          echo "Bye yet again"
      - name: checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            developers
            qa-team
          milestone: 1
          draft: false
      




