# nome do workflow
name: Meu primeiro workflow

# evento, ou seja, quando ele entra em execução
on: 
  push:
    branches:
      - develop

# especificando os jobs deste workflow
jobs:
  
  # nome do primeiro job
  primeiro_job:
    # runner do primeiro job
    runs-on: ubuntu-latest
    steps: 
      # primeiro step
      - name: Hello, Github Actions!
        run: echo "Hello, Github Actions!"
      #segundo step
      - name: Qual o direotrio atual?
        run: pwd
      # terceiro step
      - name: Qual o conteúdo do diretório, incluindo arquivos ocultos?
        run: ls -a
      - name: Até mais!
        run: |
          echo "See you, Github Action!"
          echo "Bye!"
          echo "Bye yet again"
      - name: checkout
        uses: actions/checkout@v2
      - name: pull-request
        run: |
          pr_exists=$(gh pr list --base main --head ${{ github.ref_name }} --state open --json number -q ".[].number")

          echo "$pr_exists"

          if [[ "$pr_exists" =~ [0-9]+ ]]; then
            pr_number=$(echo "$pr_exists" | head -n 1)
            gh pr edit "$pr_number" --title "Minha Pull Request (Atualizada)" --body "Aqui está a minha PR atualizada"
          else
            gh pr create --head ${{ github.ref_name }} --base main --title "Pull request title" --body "Pull request body"
          fi
          echo "teste 2"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      




